=== StephanKa/DataLayerGenerator/src/generator/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Enums": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "type": {
              "type": "string"
            },
            "values": {
              "type": "array",
              "items": [
                {
                  "type": "string"
                }
              ]
            },
            "autoId": {
              "type": "boolean"
            }
          },
          "required": [
            "name",
            "type",
            "values",
            "autoId"
          ]
        }
      ]
    },
    "Groups": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "persistence": {
              "type": "string"
            },
            "baseId": {
              "type": "string"
            },
            "version": {
              "type": "object",
              "properties": {
                "major": {
                  "type": "integer"
                },
                "minor": {
                  "type": "integer"
                },
                "build": {
                  "type": "integer"
                }
              },
              "required": [
                "major",
                "minor",
                "build"
              ]
            }
          },
          "required": [
            "name",
            "persistence",
            "baseId",
            "version"
          ]
        }
      ]
    },
    "Structs": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "parameter": {
              "type": "array"
            }
          },
          "required": [
            "name",
            "parameter"
          ]
        }
      ]
    },
    "Datapoints": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "group": {
              "type": "string"
            },
            "id": {
              "type": "integer"
            },
            "type": {
              "type": "string"
            },
            "access": {
              "type": "string"
            },
            "namespace": {
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "group",
            "id",
            "type",
            "access",
            "version"
          ]
        }
      ]
    }
  },
  "required": [
    "Enums",
    "Groups",
    "Structs",
    "Datapoints"
  ]
}

=== StephanKa/DataLayerGenerator/src/model/model.json
{
  "Enums": [
    {
      "name": "Status",
      "type": "uint32_t",
      "values": ["Booting", "Starting", "Finished"],
      "autoId": true
    },
    {
      "name": "ErrorStates",
      "type": "uint32_t",
      "values": [
        {
          "name": "Info",
          "value": 1
        },
        {
          "name": "Warn",
          "value": 4
        },
        {
          "name": "Error",
          "value": 5
        },
        {
          "name": "Critical",
          "value": 9
        },
        {
          "name": "Fatal",
          "value": 10
        }
      ],
      "autoId": false
    }
  ],
  "Groups": [
    {
      "name": "DefaultGroup",
      "persistence": "None",
      "baseId": "0x4000",
      "version": {
        "major": 1,
        "minor": 0,
        "build": 1
      }
    },
    {
      "name": "CyclicGroup",
      "persistence": "Cyclic",
      "baseId": "0x5000",
      "version": {
        "major": 2,
        "minor": 0,
        "build": 0
      }
    }
  ],
  "Structs": [
    {
      "name": "Temperature",
      "parameter": [
        {
          "name": "value",
          "type": "float"
        },
        {
          "name": "raw",
          "type": "uint32_t"
        }
      ]
    }
  ],
  "Datapoints": [
    {
      "name": "test",
      "group": "DefaultGroup",
      "id": 1,
      "type": "int32_t",
      "access": "READWRITE",
      "namespace": "Testify",
      "version": {
        "major": 1,
        "minor": 0,
        "build": 1
      }
    },
    {
      "name": "est2",
      "group": "DefaultGroup",
      "id": 2,
      "type": "int32_t",
      "access": "READWRITE",
      "namespace": "Testify",
      "version": {
        "major": 1,
        "minor": 0,
        "build": 1
      }
    },
    {
      "name": "test3",
      "group": "DefaultGroup",
      "id": 3,
      "type": "int32_t",
      "access": "READWRITE",
      "version": {
        "major": 1,
        "minor": 0,
        "build": 1
      }
    },
    {
      "name": "test4",
      "group": "CyclicGroup",
      "id": 4,
      "type": "Temperature",
      "access": "READWRITE",
      "version": {
        "major": 1,
        "minor": 0,
        "build": 1
      }
    }
  ]
}
